services:
  - type: web
    name: telegram-bot
    env: python
    region: oregon
    plan: free
    runtime: python
    version: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
